# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0002_auto_20161021_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='person',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
