# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0003_auto_20161021_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='person',
            new_name='person_id',
        ),
    ]
