# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0004_auto_20161021_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=models.ImageField(upload_to='upload/church_directory/person/pictures'),
        ),
    ]
