# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-21 22:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0007_person_is_member'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='MembershipStatusChange',
        ),
    ]
