# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0011_auto_20161208_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='unit_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Unit Number'),
        ),
    ]
