# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 08:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0009_auto_20170919_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClearanceType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
                ('duration', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='clearance',
            name='clearance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_directory.ClearanceType'),
        ),
        migrations.AddField(
            model_name='clearance',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_directory.Person'),
        ),
    ]
