# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipStatusChange',
            fields=[
                ('person', models.IntegerField(primary_key=True, serialize=False)),
                ('begin_date', models.DateField()),
                ('end_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('suffix', models.CharField(blank=True, max_length=5, null=True, verbose_name='Suffix')),
                ('sex', models.IntegerField(choices=[(0, 'Male'), (1, 'Female')])),
                ('birthday', models.DateField()),
                ('email_address', models.CharField(max_length=75, verbose_name='Email Address')),
                ('address_line1', models.CharField(max_length=50, verbose_name='Address Line 1')),
                ('address_line2', models.CharField(blank=True, max_length=50, null=True, verbose_name='Address Line 2')),
                ('apt_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Apartment Number')),
                ('membership_status', models.IntegerField(choices=[(0, 'Non-member'), (1, 'Member'), (2, 'Former Member')])),
                ('picture', models.ImageField(blank=True, null=True, upload_to='upload/church_directory/person/pictures')),
            ],
            options={
                'verbose_name_plural': 'People',
            },
        ),
    ]
