# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-22 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', 'default_values'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clearancetype',
            options={'verbose_name': 'Clearance Type'},
        ),
    ]
