# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-20 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0001_auto_20170920_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='clearancetype',
            name='builtin',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
