# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-16 11:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0001_auto_20170916_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventtype',
            options={'verbose_name': 'Event Type'},
        ),
    ]
