# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 03:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0002_auto_20161022_0343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='apt_number',
            new_name='unit_number',
        ),
        migrations.AlterField(
            model_name='person',
            name='cell_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Cell Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='home_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Home Number'),
        ),
        migrations.AlterField(
            model_name='person',
            name='membership_status',
            field=models.IntegerField(choices=[(0, 'Non-member'), (1, 'Member'), (2, 'Homebound Member'), (3, 'Out-of-area Member'), (4, 'Former Member')]),
        ),
    ]
