# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-17 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0003_auto_20170917_0413'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='zipcode',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Zip Code'),
        ),
    ]
