# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 05:30
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0004_auto_20161022_0433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to='images/church_directory/person/pictures'),
        ),
    ]
