# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-18 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0004_person_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='homebound',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='out_of_area',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
