# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-22 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0005_auto_20161022_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='email_address',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='person',
            name='membership_status',
            field=models.IntegerField(choices=[(0, 'Non-member'), (1, 'Active Member'), (2, 'Homebound Member'), (3, 'Out-of-area Member'), (4, 'Former Member')]),
        ),
    ]
