# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0005_auto_20170918_2315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='RoleAssignment',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Role Assignment',
            },
        ),
        migrations.AlterField(
            model_name='person',
            name='membership_status',
            field=models.IntegerField(choices=[(0, 'Non-member'), (1, 'Member')]),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_directory.Person'),
        ),
        migrations.AddField(
            model_name='roleassignment',
            name='role_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='church_directory.Role'),
        ),
    ]
