# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0006_auto_20170919_0806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='membership_status',
            new_name='member',
        ),
    ]
