# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 00:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0007_auto_20161023_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_child', to='church_directory.Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Middle Name'),
        ),
        migrations.AddField(
            model_name='person',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_child', to='church_directory.Person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to='images/church_directory/person/pictures'),
        ),
    ]
