# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 01:39
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0008_auto_20161026_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='membership_status',
            field=models.IntegerField(choices=[(0, 'Non-member'), (1, 'Active Member'), (2, 'Homebound Member'), (3, 'Out-of-area Member')]),
        ),
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to='./images/church_directory/person/pictures'),
        ),
    ]
