# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-19 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0008_auto_20170919_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtype',
            name='builtin',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='member',
            field=models.BooleanField(choices=[(False, 'Non-member'), (True, 'Member')]),
        ),
    ]
