# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0010_auto_20161208_0504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='membership_status',
            field=models.IntegerField(choices=[(0, 'Non-member'), (1, 'Active Member'), (2, 'Homebound Member'), (3, 'Out-of-area Member'), (4, 'Former Member'), (5, 'Deceased')]),
        ),
    ]
