# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-15 19:54
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0012_auto_20161208_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='picture',
            field=django_resized.forms.ResizedImageField(blank=True, null=True, upload_to='images/church_directory/person/pictures'),
        ),
    ]
