# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 05:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0013_auto_20170115_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='spouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='person_spouse', to='church_directory.Person'),
        ),
    ]
