# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-22 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0014_person_spouse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='cell_number',
            new_name='cell_phone',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='home_number',
            new_name='home_phone',
        ),
        migrations.RemoveField(
            model_name='person',
            name='unit_number',
        ),
        migrations.AddField(
            model_name='person',
            name='marital_status',
            field=models.IntegerField(choices=[(0, b'N/A'), (1, b'Single'), (2, b'Married')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name=b'notes'),
        ),
        migrations.AlterField(
            model_name='person',
            name='address_line1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=b'Address Line 1'),
        ),
        migrations.AlterField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True),
        ),
    ]
