# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0016_auto_20170916_0407'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
        ),
    ]
