# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 04:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion

from church_directory.models import EVENT_BAPTISM, EVENT_DEATH, EVENT_WEDDING

default_event_types = [
    EVENT_BAPTISM,
    EVENT_DEATH,
    EVENT_WEDDING,
]

def setup_event_types(apps, schema_editor):
    EventType = apps.get_model('church_directory', 'EventType')
    for v in default_event_types:
        EventType(name=v).save()

def delete_event_types(apps, schema_editor):
    EventType = apps.get_model('church_directory', 'EventType')
    for v in default_event_types:
        EventType.objects.filter(name=v).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('church_directory', '0019_event_event_type'), # required for setup_event_types
    ]

    operations = [
        migrations.RunPython(setup_event_types, delete_event_types),
    ]
